name: tests-auth

on:
  pull_request:
    paths:
      - 'auth2/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth2 && npm install && npm run test
